### PR TITLE
Use PoPS Core with overpopulation movements

### PR DESCRIPTION
**Pull request by wenzeslaus**
This uses a separate overpopulation_config which is actually passed to the C++ pops_model function.

The config contains three doubles and it is `List` in C++. I'm not sure if NumericalVector would be more appropriate, however in R it is a List since it has named elements. (In C++ NumericalVector can have named elements, but in R it is coerced to a list AFAIU.)

It could be also a Rcpp nullable parameter, but we pass the boolean elsewhere anyway, so it is boolean plus config.

The translation from individual parameters to the double-only config list is done in the R pops_model function before it is passed to C++ pops_model_cpp function, so pops_model does more than just call the C++ function. It hides the difficulties in calling a C++ function, i.e., the parameter number limit. (Later, pops_model or another function, it could translate from whatever "config" used in R to whatever combo of "configs" the C++ will need.)

### CODE REVIEW

**Comment by ChrisJones687** [comment]
@wenzeslaus the pops_model r wrapper for the pops_model_cpp function is now merged into master and will make the documentation process easier going forward.

**Comment by wenzeslaus** [comment]
I have updated the description to reflect the current state.

It has tests in core, but none here yet. Maybe for a different PR just to get things in for further experiments?

@ChrisJones687 Let me know what you think.

**Comment by wenzeslaus** [comment]
Using `List::create()` to make the parameter optional causes _"Unable to parse C++ default value 'List::create()' for argument overpopulation_config of function pops_model_cpp"_. The compilation and tests pass, but according to the documentation `::create()` works only for the NumericVector etc. However, input list fails to convert when NumericVector is used as a parameter. The correct solution here is to make it "nullable" with `Nullable<List>` and set the default to `R_NilValue`.

The test of use_overpopulation_movements boolean is preserved to keep it explicit (we can consider removing it, but it works in any context, e.g., in pure C++ config in Core). However, the test is extended by `config.isNotNull()` to check it is not null before accessing it, i.e., it just ignores use_overpopulation_movements that is true if config is null.

There is also `isUsable()` but I see only `isNotNull()` being used. The difference is that `isNotNull()` throws an exception if the variable was not set which would be a programmer error, so it seems like the right function to use.

A bonus of `Nullable<List>` is that it is similar to C++17 std::optional, so pretty much standard for representing "possibly no value" values in C++.

**Comment by ChrisJones687** [comment]
This all looks good. I will add tests for overpopulation to issue #51 for a future PR.

**Review by ChrisJones687 — APPROVED** [review]

**Pull request merged**
